debug: true

server:
  port: 8080

app:
  cors:
    url: http://localhost:3000
  jwt:
    secret: a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26
    expiration-duration: 1D

spring:
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 50
  datasource:
    url: jdbc:postgresql://localhost:5432/data_integration
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver